"""initial

Revision ID: f8c560350b97
Revises: 
Create Date: 2026-03-22 03:56:01.397260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8c560350b97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=False),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('cert_path', sa.Text(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('max_output_tokens', sa.Integer(), nullable=False),
    sa.Column('use_max_completion_tokens', sa.Boolean(), nullable=False),
    sa.Column('concurrency', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('repo_path', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('llm_profile_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_phase', sa.String(length=50), nullable=True),
    sa.Column('current_task', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('files_processed', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('files_total', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('findings_count', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('progress', sa.Float(), nullable=False, server_default='0.0'),
    sa.Column('ai_calls_made', sa.Integer(), nullable=False, server_default='0'),
    sa.ForeignKeyConstraint(['llm_profile_id'], ['llm_profiles.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('agent', sa.String(length=50), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('files_inspected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_decisions_scan_id'), 'agent_decisions', ['scan_id'], unique=False)
    op.create_table('compaction_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compaction_summaries_scan_id'), 'compaction_summaries', ['scan_id'], unique=False)
    op.create_table('dependencies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('ecosystem', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('is_dev', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependencies_scan_id'), 'dependencies', ['scan_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('line_count', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('score_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('is_config', sa.Boolean(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id', 'path')
    )
    op.create_index(op.f('ix_files_scan_id'), 'files', ['scan_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cwe_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exploit_difficulty', sa.String(length=20), nullable=True),
    sa.Column('exploit_prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('exploit_template', sa.Text(), nullable=True),
    sa.Column('related_cves', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attack_scenario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_scan_id'), 'findings', ['scan_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('app_summary', sa.Text(), nullable=True),
    sa.Column('architecture', sa.Text(), nullable=True),
    sa.Column('diagram_spec', sa.Text(), nullable=True),
    sa.Column('diagram_image', sa.LargeBinary(), nullable=True),
    sa.Column('methodology', sa.Text(), nullable=True),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scanner_hits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attack_surface', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_grade', sa.String(length=2), nullable=True),
    sa.Column('owasp_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('component_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sbom', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scan_coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('report_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('scan_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('scanners', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('semgrep_version', sa.String(length=50), nullable=True),
    sa.Column('bandit_version', sa.String(length=50), nullable=True),
    sa.Column('eslint_version', sa.String(length=50), nullable=True),
    sa.Column('advisory_db_ver', sa.String(length=50), nullable=True),
    sa.Column('llm_model', sa.String(length=255), nullable=True),
    sa.Column('scan_mode', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    op.create_table('scan_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_events_scan_id'), 'scan_events', ['scan_id'], unique=False)
    op.create_table('dependency_findings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dependency_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('advisory_id', sa.String(length=100), nullable=True),
    sa.Column('cve_id', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('affected_range', sa.String(length=200), nullable=True),
    sa.Column('fixed_version', sa.String(length=100), nullable=True),
    sa.Column('cwes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('vulnerable_functions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('relevance', sa.String(length=20), nullable=False),
    sa.Column('ai_assessment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependencies.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependency_findings_scan_id'), 'dependency_findings', ['scan_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('code_snippet', sa.Text(), nullable=True),
    sa.Column('line_range', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('layer', sa.String(length=50), nullable=True),
    sa.Column('security_notes', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding_files',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('finding_id', 'file_id')
    )
    op.create_table('scanner_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('scanner', sa.String(length=50), nullable=False),
    sa.Column('rule_id', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scanner_results_file_id'), 'scanner_results', ['file_id'], unique=False)
    op.create_index(op.f('ix_scanner_results_scan_id'), 'scanner_results', ['scan_id'], unique=False)
    op.create_table('secret_candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value_preview', sa.String(length=20), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('is_false_positive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_candidates_scan_id'), 'secret_candidates', ['scan_id'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=True),
    sa.Column('end_line', sa.Integer(), nullable=True),
    sa.Column('signature', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbols_file_id'), 'symbols', ['file_id'], unique=False)
    op.create_index(op.f('ix_symbols_scan_id'), 'symbols', ['scan_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scan_id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('symbol_id', sa.Uuid(), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path_pattern', sa.Text(), nullable=True),
    sa.Column('auth_required', sa.Boolean(), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_scan_id'), 'routes', ['scan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routes_scan_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_symbols_scan_id'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_file_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_secret_candidates_scan_id'), table_name='secret_candidates')
    op.drop_table('secret_candidates')
    op.drop_index(op.f('ix_scanner_results_scan_id'), table_name='scanner_results')
    op.drop_index(op.f('ix_scanner_results_file_id'), table_name='scanner_results')
    op.drop_table('scanner_results')
    op.drop_table('finding_files')
    op.drop_table('file_summaries')
    op.drop_table('export_artifacts')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_dependency_findings_scan_id'), table_name='dependency_findings')
    op.drop_table('dependency_findings')
    op.drop_index(op.f('ix_scan_events_scan_id'), table_name='scan_events')
    op.drop_table('scan_events')
    op.drop_table('scan_configs')
    op.drop_table('reports')
    op.drop_index(op.f('ix_findings_scan_id'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_files_scan_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_dependencies_scan_id'), table_name='dependencies')
    op.drop_table('dependencies')
    op.drop_index(op.f('ix_compaction_summaries_scan_id'), table_name='compaction_summaries')
    op.drop_table('compaction_summaries')
    op.drop_index(op.f('ix_agent_decisions_scan_id'), table_name='agent_decisions')
    op.drop_table('agent_decisions')
    op.drop_table('scans')
    op.drop_table('projects')
    op.drop_table('llm_profiles')
    # ### end Alembic commands ###
